package com.dubitaxi.ui.selectUserType.driverSignUp.bankDetails.vo

data class DriverData(
    val _id: String,
    val access_token: String,
    val city: String,
    val country: Any,
    val country_code: String,
    val createdAt: String,
    val device_token: String,
    val device_type: Int,
    val email: String,
    val full_name: String,
    val gender: Int,
    val identity_card: List<String>,
    val is_blocked: Boolean,
    val is_email_verified: Int,
    val is_mobile_verified: Int,
    val is_profile_complete: Int,
    val last_login: Long,
    val latitude: Double,
    val location: Location,
    val longitude: Double,
    val otp: String,
    val otpValidityTill: Long,
    val permit_smoking: Boolean,
    val pets_accepted: Boolean,
    val phone_number: String,
    val profile_picture: String,
    val referred_by: String,
    val service_offerings: List<Any>,
    val smoker: Boolean,
    val status: Int,
    val updatedAt: String,
    val verification_document: VerificationDocument,
    val wallet_id: String
)